### PR TITLE
Move Sleef module to top Libm.jl level

### PR DESCRIPTION
**Pull request by musm**
Remove Sleef module in favor of the top level Libm.jl level and move all
the corresponding files to the top level as well.

### CODE REVIEW

**Comment by simonbyrne** [comment]
Did you want to remove the x prefixes from the function names as well?

**Comment by musm** [comment]
Good call, I left them there since it's easy to test with the x prefix instead of having to qualify all the function names. Do you have any thoughts on the Musl module? Should it be renamed or moved to another package?

**Comment by simonbyrne** [comment]
I actually don't mind the current module layout (you can always `using Libm.Sleef` to import the names), but since you're doing all the work I'll leave the bikeshedding up to you.

I would be in favour of keeping the existing Musl code, we can always remove it when it gets moved to Base.

**Comment by musm** [comment]
Updated and removed x prefix, now  Sleef calls should be qualified, i.e. `Libm.sin` and Musl as `Libm.Musl.erf`

**Pull request merged**
